import { Toaster } from "_/components/ui/sonner";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Exo, Geist, Geist_Mono } from "next/font/google";
import Footer from "./_components/Footer/Footer";
import Header from "./_components/Header/Header";
import Navbar from "./_components/Navbar/Navbar";
import "./globals.css";
import WrapperForSessionProvider from "./_components/WrapperForSessionProvider/WrapperForSessionProvider";
import CartContextProvider from "./_context/CartContext";
import WishlistProvider from "./_context/WishlistContext";
import { getUserCart, getUserWishlist } from "_/api/services/route.services";
import { cartResponse } from "_/api/services/types";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Fresh Cart",
    template: "Fresh Cart | %s",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // calling api cart
  const res = await getUserCart();
  const resFromWishlist = await getUserWishlist();
  // (res as cartResponse).products
  // const initialNumberOfCartItems = res?.numOfCartItems ?? 0;

  return (
    <html lang="en">
      <body
        className={`${exo.className} ${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
        <WrapperForSessionProvider>
          <WishlistProvider res={resFromWishlist}>
            <CartContextProvider res={res}>
              <Header />

              <Navbar />
              {children}
              <Toaster duration={3000} />
              <Footer />
            </CartContextProvider>
          </WishlistProvider>
        </WrapperForSessionProvider>
      </body>
    </html>
  );
}
